<script setup lang="ts">import { onMounted,ref } from 'vue'; import { ElMessage,ElMessageBox } from 'element-plus'; import { http,messageOf } from '@/api/http'; import UploadDialog from '@/components/UploadDialog.vue'; import QrCodeDialog from '@/components/QrCodeDialog.vue';
interface Video{id:string;publicId:string;name:string;originalName:string;mimeType:string;size:string;viewCount:number;playCount:number;status:'ACTIVE'|'DISABLED';createdAt:string;uploader:{username:string}}
const items=ref<Video[]>([]),total=ref(0),page=ref(1),keyword=ref(''),loading=ref(false),upload=ref(false),qrVideo=ref<Video>(); async function load(){loading.value=true;try{const {data}=await http.get('/videos',{params:{page:page.value,pageSize:20,keyword:keyword.value}});items.value=data.items;total.value=data.total}catch(e){ElMessage.error(messageOf(e))}finally{loading.value=false}}
async function rename(v:Video){try{const {value}=await ElMessageBox.prompt('输入新名称','重命名',{inputValue:v.name,inputPattern:/\S+/,inputErrorMessage:'名称不能为空'});await http.patch(`/videos/${v.id}`,{name:value.trim()});ElMessage.success('已保存');load()}catch{}}
async function toggle(v:Video){try{if(v.status==='ACTIVE')await ElMessageBox.confirm('停用后公开地址将无法播放。','停用视频',{type:'warning'});await http.patch(`/videos/${v.id}`,{status:v.status==='ACTIVE'?'DISABLED':'ACTIVE'});ElMessage.success(v.status==='ACTIVE'?'已停用':'已启用');load()}catch{}}
async function remove(v:Video){try{await ElMessageBox.confirm(`将永久删除“${v.name}”及服务器文件，无法恢复。`,'删除视频',{type:'error',confirmButtonText:'删除'});await http.delete(`/videos/${v.id}`);ElMessage.success('已删除');load()}catch{}}
async function copy(v:Video){await navigator.clipboard.writeText(`${location.origin}/watch/${v.publicId}`);ElMessage.success('地址已复制')} function size(n:string){const x=Number(n);return x<1024**3?`${(x/1024**2).toFixed(1)} MB`:`${(x/1024**3).toFixed(2)} GB`} function date(s:string){return new Date(s).toLocaleString('zh-CN',{hour12:false})} onMounted(load);
function play(v:Video){window.open(`/watch/${v.publicId}`,'_blank','noopener')}
function publicUrl(v:Video){return `${location.origin}/watch/${v.publicId}`}
function showQr(v:Video){qrVideo.value=v}
</script>
<template><div class="page"><div class="toolbar"><el-input v-model="keyword" clearable placeholder="搜索视频" style="max-width:260px" @keyup.enter="page=1;load()" @clear="page=1;load()"/><el-button @click="page=1;load()">查询</el-button><span class="grow"></span><el-button type="primary" @click="upload=true">上传视频</el-button></div><el-table v-loading="loading" :data="items" row-key="id"><el-table-column label="名称" min-width="190"><template #default="{row}"><div class="name">{{row.name}}</div><div class="muted">{{size(row.size)}} · {{row.mimeType}}</div></template></el-table-column><el-table-column prop="uploader.username" label="上传者" width="110" class-name="desktop-only"/><el-table-column label="时间" width="170" class-name="desktop-only"><template #default="{row}">{{date(row.createdAt)}}</template></el-table-column><el-table-column label="浏览 / 播放" width="120" align="center"><template #default="{row}">{{row.viewCount}} / {{row.playCount}}</template></el-table-column><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.status==='ACTIVE'?'success':'info'" effect="plain">{{row.status==='ACTIVE'?'正常':'已停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="320" fixed="right"><template #default="{row}"><el-button link type="primary" :disabled="row.status!=='ACTIVE'" @click="play(row)">播放</el-button><el-button link @click="copy(row)">复制</el-button><el-button link @click="showQr(row)">二维码</el-button><el-dropdown trigger="click"><el-button link class="more">更多</el-button><template #dropdown><el-dropdown-menu><el-dropdown-item @click="rename(row)">重命名</el-dropdown-item><el-dropdown-item @click="toggle(row)">{{row.status==='ACTIVE'?'停用':'启用'}}</el-dropdown-item><el-dropdown-item divided class="danger" @click="remove(row)">删除</el-dropdown-item></el-dropdown-menu></template></el-dropdown></template></el-table-column></el-table><div class="pager"><el-pagination v-model:current-page="page" background layout="prev,pager,next" :total="total" :page-size="20" @current-change="load"/></div><UploadDialog v-model="upload" @done="page=1;load()"/><QrCodeDialog :model-value="!!qrVideo" :url="qrVideo?publicUrl(qrVideo):''" :name="qrVideo?.name||''" @update:model-value="value=>{if(!value)qrVideo=undefined}"/></div></template>
<style scoped>.name{font-weight:500;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.more{margin-left:12px}.pager{display:flex;justify-content:flex-end;margin-top:16px}@media(max-width:700px){:deep(.el-table__fixed-right){width:220px!important}:deep(.el-table__fixed-right .el-table__cell){width:220px!important}.el-table{font-size:13px}}</style>
